# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntext.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\">\n\x0cTextResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\"\x1a\n\tTextIndex\x12\r\n\x05index\x18\x01 \x01(\x05\x32\x65\n\x0bTextService\x12\'\n\x08SaveText\x12\x0c.TextRequest\x1a\r.TextResponse\x12-\n\x10GetTextTimestamp\x12\n.TextIndex\x1a\r.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEXTREQUEST']._serialized_start=14
  _globals['_TEXTREQUEST']._serialized_end=41
  _globals['_TEXTRESPONSE']._serialized_start=43
  _globals['_TEXTRESPONSE']._serialized_end=105
  _globals['_TEXTINDEX']._serialized_start=107
  _globals['_TEXTINDEX']._serialized_end=133
  _globals['_TEXTSERVICE']._serialized_start=135
  _globals['_TEXTSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
