# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: division.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ivision.proto\"2\n\rDivideRequest\x12\x10\n\x08\x64ividend\x18\x01 \x01(\x01\x12\x0f\n\x07\x64ivisor\x18\x02 \x01(\x01\" \n\x0e\x44ivideResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32<\n\x0f\x44ivisionService\x12)\n\x06\x44ivide\x12\x0e.DivideRequest\x1a\x0f.DivideResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'division_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIVIDEREQUEST']._serialized_start=18
  _globals['_DIVIDEREQUEST']._serialized_end=68
  _globals['_DIVIDERESPONSE']._serialized_start=70
  _globals['_DIVIDERESPONSE']._serialized_end=102
  _globals['_DIVISIONSERVICE']._serialized_start=104
  _globals['_DIVISIONSERVICE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
